/**
 * @file Version.h
 * @brief Version information for OPT4001.
 *
 * This file is AUTO-GENERATED by scripts/generate_version.py from library.json.
 * DO NOT EDIT MANUALLY. Update version metadata via library.json or
 * scripts/generate_version.py bump/set commands.
 */

#pragma once

#include <stdint.h>

#ifndef OPT4001_VERSION_STRING
#define OPT4001_VERSION_STRING "1.1.1"
#endif

#ifndef OPT4001_BUILD_DATE
#define OPT4001_BUILD_DATE "unknown"
#endif

#ifndef OPT4001_BUILD_TIME
#define OPT4001_BUILD_TIME "unknown"
#endif

#ifndef OPT4001_BUILD_TIMESTAMP
#define OPT4001_BUILD_TIMESTAMP "unknown"
#endif

#ifndef OPT4001_GIT_COMMIT
#define OPT4001_GIT_COMMIT "unknown"
#endif

#ifndef OPT4001_GIT_STATUS
#define OPT4001_GIT_STATUS "unknown"
#endif

#ifndef OPT4001_VERSION_FULL
#define OPT4001_VERSION_FULL OPT4001_VERSION_STRING " (" OPT4001_GIT_COMMIT ", " OPT4001_BUILD_TIMESTAMP ", " OPT4001_GIT_STATUS ")"
#endif

namespace OPT4001 {

/// @brief Major version (breaking changes).
static constexpr uint16_t VERSION_MAJOR = 1;

/// @brief Minor version (backward-compatible features).
static constexpr uint16_t VERSION_MINOR = 1;

/// @brief Patch version (backward-compatible fixes).
static constexpr uint16_t VERSION_PATCH = 1;

/// @brief Full semantic version string.
static constexpr const char* VERSION = OPT4001_VERSION_STRING;

/// @brief Encoded version for numeric comparison: MAJOR*10000 + MINOR*100 + PATCH.
static constexpr uint32_t VERSION_CODE = 10101;

/// @brief Backward-compatible alias used by older repositories.
static constexpr int VERSION_INT = 10101;

/// @brief Build date string.
static constexpr const char* BUILD_DATE = OPT4001_BUILD_DATE;

/// @brief Build time string.
static constexpr const char* BUILD_TIME = OPT4001_BUILD_TIME;

/// @brief Build timestamp string.
static constexpr const char* BUILD_TIMESTAMP = OPT4001_BUILD_TIMESTAMP;

/// @brief Git commit string.
static constexpr const char* GIT_COMMIT = OPT4001_GIT_COMMIT;

/// @brief Git working tree status string.
static constexpr const char* GIT_STATUS = OPT4001_GIT_STATUS;

/// @brief Full version string with build metadata.
static constexpr const char* VERSION_FULL = OPT4001_VERSION_FULL;

}  // namespace OPT4001
